spring:
  profiles:
    active: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mvc:
    path-match:
      matching-strategy: ant_path_matcher