spring:
  data:
    redis:
      host: ${HOST}
      port: ${REDIS_PORT}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${HOST}:3306/springles
    username: ${MYSQL_ROOT_USER}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: ${NAVER_MAIL_PORT}
    NAVER_MAIL_USERNAME: ${NAVER_MAIL_USERNAME}
    NAVER_MAIL_PASSWORD: ${NAVER_MAIL_PASSWORD}

jwt:
  secret: dhwhokdfnpwkempfnwiofnpwkempfnwiofnpwkempfnwiofnpwkempfnwio